name: lstm-text-gen
channels:
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.5
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyter
    - tensorflow
    - keras
    - pandas
